/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_jni_HelloJni */

#ifndef _Included_com_test_jni_HelloJni
#define _Included_com_test_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_jni_HelloJni
 * Method:    getNativeStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_jni_HelloJni_getNativeStr
  (JNIEnv *, jobject);

/*
 * Class:     com_test_jni_HelloJni
 * Method:    setVlanId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_test_jni_HelloJni_setVlanId
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_test_jni_HelloJni
 * Method:    getIsSucess
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_test_jni_HelloJni_getIsSucess
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
